#!/usr/bin/env python3
"""Create a parent-agent editable review observations template."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from core.demo_review import build_review_observation_template


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Seed a structured review observations template after a frames-only spawned sub-agent gut check."
    )
    parser.add_argument("--bundle-manifest", required=True, help="Processed capture bundle manifest JSON.")
    parser.add_argument("--output-json", required=True, help="Where to write the editable observations template JSON.")
    parser.add_argument(
        "--review-frames-manifest",
        help="Optional review_frames.json generated by extract_review_frames.py for clip/frame mapping.",
    )
    parser.add_argument(
        "--raw-review-path",
        default="",
        help="Optional path to the saved raw spawned sub-agent response.",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    bundle_manifest = json.loads(Path(args.bundle_manifest).read_text(encoding="utf-8"))
    review_frames_manifest = None
    if args.review_frames_manifest:
        review_frames_manifest = json.loads(Path(args.review_frames_manifest).read_text(encoding="utf-8"))

    template = build_review_observation_template(
        bundle_manifest,
        review_frames_manifest=review_frames_manifest,
        raw_feedback_path=args.raw_review_path,
    )
    output_path = Path(args.output_json).expanduser().resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(json.dumps(template, indent=2), encoding="utf-8")
    print(json.dumps(template, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
